In [1]:
%cd ../mcmetrics

from main import MCMetrics as MCMetrics

c:\Users\cbsit\Dropbox\GitHub\mcmetrics\mcmetrics


In [2]:
assert MCMetrics is not None, "MCMetrics cannot be imported"

In [3]:
def test_mcmetrics_class_instance():
    """Test if an instance of MCMetrics can be created."""
    obj = MCMetrics()  # add required args if any
    assert isinstance(obj, MCMetrics), "Should create an instance of MCMetrics"

In [4]:
import numpy as np

cm1 = np.array([[100,10],
                [10,100]])

test1 = MCMetrics(model_name="model_1", cm=cm1)

test1.model_name, test1.cm, test1.class_names

('model_1',
 array([[100.,  10.],
        [ 10., 100.]]),
 ['Class 0', 'Class 1'])

In [5]:
test1.retrieve_metrics_list()

['prevalence',
 'accuracy',
 'balanced accuracy',
 'precision',
 'positive predictive value',
 'false discovery rate',
 'f1 score',
 'false omission rate',
 'negative predictive value',
 'fowlkes-mallows index',
 'informedness',
 'sensitivity',
 'true positive rate',
 'recall',
 'false positive rate',
 'positive likelihood ratio',
 'markedness',
 'true negative rate',
 'matthews correlation coefficient',
 'prevalence threshold',
 'false negative rate',
 'specificity',
 'negative likelihood ratio',
 'diagnostic odds ratio',
 'jaccard index',
 'critical success index',
 'threat score',
 'screening coefficient',
 'cohens kappa']

In [6]:
cm1.shape

(2, 2)

In [7]:
test1.sample(n=1000, include_prior=True, resample=False)
test1.posterior_samples, test1.sample_size

(array([[[0.4603885 , 0.02419046],
         [0.04366756, 0.47175348]],
 
        [[0.44505076, 0.05898023],
         [0.02638647, 0.46958254]],
 
        [[0.48601736, 0.05553258],
         [0.0719362 , 0.38651385]],
 
        ...,
 
        [[0.45054008, 0.04938354],
         [0.03342616, 0.46665022]],
 
        [[0.43529668, 0.03542099],
         [0.09873087, 0.43055146]],
 
        [[0.42764228, 0.03502103],
         [0.07174344, 0.46559325]]], shape=(1000, 2, 2)),
 1000)

In [8]:
test1.posterior_samples.shape

(1000, 2, 2)

In [ ]:
test1.sample(n=1_000, include_prior=True, resample=False)
test1.posterior_samples

array([[[0.4603885 , 0.02419046],
        [0.04366756, 0.47175348]],

       [[0.44505076, 0.05898023],
        [0.02638647, 0.46958254]],

       [[0.48601736, 0.05553258],
        [0.0719362 , 0.38651385]],

       ...,

       [[0.46913393, 0.01935717],
        [0.04576296, 0.46574593]],

       [[0.4450648 , 0.05326687],
        [0.08353639, 0.41813194]],

       [[0.42606195, 0.05270341],
        [0.05292711, 0.46830753]]], shape=(101000, 2, 2))

In [ ]:
# calculate sensitivity
test1.calculate_metric(metric='sensitivity', averaging=None)
# calculate specificity
test1.calculate_metric(metric='specificity', averaging=None)
# calculate positive predictive value
test1.calculate_metric(metric='positive predictive value', averaging=None)
# cohens kappa
test1.calculate_metric(metric='cohens kappa', averaging=None)
# cohens prevalence threshold
test1.calculate_metric(metric='prevalence threshold', averaging=None)

In [22]:
# calculate credible intervals
test1.calculate_ci(metric='sensitivity', ci=0.95)

{'Class 0': array([0.84099068, 0.94948238]),
 'Class 1': array([0.8407807 , 0.94953822])}

In [23]:
# the upper and lower bounds of the credible interval can be explicited specified
test1.calculate_ci(metric='sensitivity', cil=0.005, ciu=0.99)

{'Class 0': array([0.81801388, 0.95575146]),
 'Class 1': array([0.81676118, 0.95575866])}

In [20]:
test1.calculate_metric(metric='prevalence threshold', averaging=None).calc_mean()

{'Class 0': np.float64(0.24533425213902757),
 'Class 1': np.float64(0.24520311891528834)}

In [12]:
metrics_list = ['critical success index', 'threat score', 'screening coefficient', 'cohens kappa']

test1.calculate_metric(metric=metrics_list, averaging=None)

In [13]:
test1.metrics

{'sensitivity': array([[0.91336766, 0.95122341],
        [0.94402974, 0.88841395],
        [0.87107134, 0.87437387],
        ...,
        [0.91112209, 0.96009679],
        [0.84196708, 0.88700254],
        [0.88950247, 0.89884395]], shape=(101000, 2)),
 'specificity': array([[0.95122341, 0.91336766],
        [0.88841395, 0.94402974],
        [0.87437387, 0.87107134],
        ...,
        [0.96009679, 0.91112209],
        [0.88700254, 0.84196708],
        [0.89884395, 0.88950247]], shape=(101000, 2)),
 'precision': array([[0.91336766, 0.95122341],
        [0.94402974, 0.88841395],
        [0.87107134, 0.87437387],
        ...,
        [0.91112209, 0.96009679],
        [0.84196708, 0.88700254],
        [0.88950247, 0.89884395]], shape=(101000, 2)),
 'cohens_kappa': array([[0.86431792, 0.86431792],
        [0.8293452 , 0.8293452 ],
        [0.74258302, 0.74258302],
        ...,
        [0.86984899, 0.86984899],
        [0.72644569, 0.72644569],
        [0.78836126, 0.78836126]], shape=(10

In [14]:
test1.calculate_ci(metric='cohens kappa', ci=0.95, cil=None, ciu=None)

{'Class 0': array([0.71812618, 0.87430025]),
 'Class 1': array([0.71812618, 0.87430025])}

In [15]:
test1.metrics

{'sensitivity': array([[0.91336766, 0.95122341],
        [0.94402974, 0.88841395],
        [0.87107134, 0.87437387],
        ...,
        [0.91112209, 0.96009679],
        [0.84196708, 0.88700254],
        [0.88950247, 0.89884395]], shape=(101000, 2)),
 'specificity': array([[0.95122341, 0.91336766],
        [0.88841395, 0.94402974],
        [0.87437387, 0.87107134],
        ...,
        [0.96009679, 0.91112209],
        [0.88700254, 0.84196708],
        [0.89884395, 0.88950247]], shape=(101000, 2)),
 'precision': array([[0.91336766, 0.95122341],
        [0.94402974, 0.88841395],
        [0.87107134, 0.87437387],
        ...,
        [0.91112209, 0.96009679],
        [0.84196708, 0.88700254],
        [0.88950247, 0.89884395]], shape=(101000, 2)),
 'cohens_kappa': array([[0.86431792, 0.86431792],
        [0.8293452 , 0.8293452 ],
        [0.74258302, 0.74258302],
        ...,
        [0.86984899, 0.86984899],
        [0.72644569, 0.72644569],
        [0.78836126, 0.78836126]], shape=(10

In [16]:
test1.metric_metadata['cohens kappa']['data array']

'cohens_kappa'

In [17]:
test1.calculate_ci(metric='sensitivity', ci=0.95, cil=None, ciu=None)

{'Class 0': array([0.84099068, 0.94948238]),
 'Class 1': array([0.8407807 , 0.94953822])}

In [18]:
# sensitivity mean calc using posterior samples, sensitivity from confusion matrix minus prior
test1.calc_mean(metric='sensitivity'), (test1.cm[0,0]+1) / (test1.cm[0,0]+1 + test1.cm[0,1]+1)

ValueError: Mean calculation is only supported for a single metric at a time. Please specify a single metric.

In [ ]:
test1.calc_mode(metric='positive predictive value')

{'Class 0': np.float64(0.9062469577557424),
 'Class 1': np.float64(0.9078740503775622)}

In [ ]:
test1.fit_beta(metric='cohens kappa')

{'Class 0': {'alpha': np.float64(79.39852647287145),
  'beta': np.float64(19.511850709967657)},
 'Class 1': {'alpha': np.float64(79.39852647287145),
  'beta': np.float64(19.511850709967653)}}

In [ ]:
test1.fit_beta(metric='prevalence threshold')

{'Class 0': {'alpha': np.float64(62.46411044028009),
  'beta': np.float64(192.1558866731993)},
 'Class 1': {'alpha': np.float64(62.7299736291572),
  'beta': np.float64(192.79225397274206)}}

In [ ]:
test1.significant_digits()

3